"""
src/motility/motility_analysis.py
===================================
Phase 4 · Motility Analysis — CASA-Inspired Metrics

Computes WHO / CASA-inspired sperm kinematics from the track CSV
generated by SpermTracker.

Metrics computed per track
--------------------------
  VCL  — Curvilinear Velocity        (µm/s) — mean frame-to-frame speed
  VSL  — Straight-Line Velocity      (µm/s) — displacement / total time
  VAP  — Average Path Velocity       (µm/s) — speed along smoothed path
  LIN  — Linearity                   VSL / VCL
  STR  — Straightness                VSL / VAP
  WOB  — Wobble                      VAP / VCL
  ALH  — Amplitude of Lateral Head   std-dev of lateral displacement (µm)
  total_distance   (µm)
  displacement     (µm)

Classification
--------------
  Progressive     — VCL ≥ 25 µm/s  AND  LIN ≥ 0.5
  Non-progressive — VCL ≥ 5 µm/s   AND  (VCL < 25 OR LIN < 0.5)
  Immotile        — VCL < 5 µm/s

Input
-----
    DataFrame from tracks.csv  (columns: frame_id, track_id, cx, cy)
    OR path to tracks.csv

Output
------
    per_track_df   — one row per track with all kinematics
    summary_dict   — {progressive%, nonprogressive%, immotile%, ...}

How to Run
----------
    python -m src.motility.motility_analysis --tracks outputs/tracking/xxx_tracks.csv
"""

import argparse
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.ndimage import uniform_filter1d

from src.utils.helpers import ensure_dir, load_config
from src.utils.logger import get_logger

logger = get_logger(__name__)


# ══════════════════════════════════════════════════════════════
# Motility Analyser
# ══════════════════════════════════════════════════════════════

class MotilityAnalyser:
    """
    CASA-inspired sperm motility analyser.

    Parameters
    ----------
    config : dict, optional
    tracks_df : pd.DataFrame, optional
        Pre-loaded tracks DataFrame.
    """

    def __init__(self, config: Optional[Dict] = None,
                 tracks_df: Optional[pd.DataFrame] = None) -> None:
        if config is None:
            config = load_config()
        self.config = config

        mot_cfg = config["motility"]
        self.fps              = mot_cfg["fps"]
        self.px2um            = mot_cfg["pixel_to_micron"]   # µm per pixel
        self.min_frames       = mot_cfg["min_track_frames"]
        self.vcl_progressive  = mot_cfg["progressive_vcl"]
        self.vcl_nonprog      = mot_cfg["nonprogressive_vcl"]
        self.lin_progressive  = mot_cfg["progressive_str"]

        self.plot_dir = ensure_dir(config["paths"]["outputs"]["plots"])

        self._tracks_df = tracks_df  # may be None until load() is called

    # ----------------------------------------------------------

    def load_tracks(self, csv_path: str | Path) -> None:
        """
        Load track CSV produced by SpermTracker.

        Parameters
        ----------
        csv_path : str | Path
        """
        self._tracks_df = pd.read_csv(csv_path)
        logger.info("Loaded {} track rows from {}", len(self._tracks_df), csv_path)

    # ----------------------------------------------------------

    def analyse(self) -> Tuple[pd.DataFrame, Dict]:
        """
        Run full motility analysis on the loaded tracks.

        Returns
        -------
        per_track_df : pd.DataFrame
            One row per track with all kinematic features.
        summary : dict
            Percentage breakdown and mean velocities.
        """
        if self._tracks_df is None or self._tracks_df.empty:
            logger.error("No tracks loaded. Call load_tracks() first.")
            return pd.DataFrame(), {}

        rows = []
        track_ids = self._tracks_df["track_id"].unique()
        logger.info("Analysing {} unique tracks", len(track_ids))

        for tid in track_ids:
            sub = (
                self._tracks_df[self._tracks_df["track_id"] == tid]
                .sort_values("frame_id")
                .reset_index(drop=True)
            )

            if len(sub) < self.min_frames:
                continue  # too short — ignore

            kinematics = self._compute_kinematics(sub)
            kinematics["track_id"] = int(tid)
            kinematics["n_frames"] = len(sub)
            rows.append(kinematics)

        if not rows:
            logger.warning("No tracks passed the minimum frame threshold")
            return pd.DataFrame(), {}

        per_track_df = pd.DataFrame(rows)
        per_track_df["motility_class"] = per_track_df.apply(
            self._classify_row, axis=1
        )

        summary = self._build_summary(per_track_df)
        self._plot_motility(per_track_df)

        logger.success(
            "Motility summary: Progressive={:.1f}% | Non-prog={:.1f}% | Immotile={:.1f}%",
            summary["progressive_pct"],
            summary["nonprogressive_pct"],
            summary["immotile_pct"],
        )

        return per_track_df, summary

    # ----------------------------------------------------------

    def _compute_kinematics(self, sub: pd.DataFrame) -> Dict:
        """
        Compute all kinematic metrics for one track.

        Parameters
        ----------
        sub : pd.DataFrame
            Rows for one track_id, sorted by frame_id.

        Returns
        -------
        dict
        """
        cxs = sub["cx"].values.astype(float) * self.px2um
        cys = sub["cy"].values.astype(float) * self.px2um
        dt  = 1.0 / self.fps   # time per frame (seconds)

        # ── Frame-to-frame distances 
        dx = np.diff(cxs)
        dy = np.diff(cys)
        frame_dists = np.hypot(dx, dy)           # µm per frame step

        total_distance = float(frame_dists.sum())
        n_steps = len(frame_dists)
        total_time = n_steps * dt

        # VCL — mean curvilinear speed
        vcl = total_distance / total_time if total_time > 0 else 0.0

        # VSL — straight-line displacement speed
        displacement = float(np.hypot(cxs[-1] - cxs[0], cys[-1] - cys[0]))
        vsl = displacement / total_time if total_time > 0 else 0.0

        # VAP — average path velocity (smoothed path using 5-point window)
        smooth_w = min(5, len(cxs))
        cxs_sm = uniform_filter1d(cxs, size=smooth_w)
        cys_sm = uniform_filter1d(cys, size=smooth_w)
        ap_dists = np.hypot(np.diff(cxs_sm), np.diff(cys_sm))
        ap_total  = float(ap_dists.sum())
        vap = ap_total / total_time if total_time > 0 else 0.0

        # Derived ratios (guard against division by zero)
        lin = vsl / vcl if vcl > 0 else 0.0
        str_ = vsl / vap if vap > 0 else 0.0
        wob  = vap / vcl if vcl > 0 else 0.0

        # ALH — amplitude of lateral head displacement
        # Lateral deviation = deviation from the average-path line
        alh = float(np.std(frame_dists)) if len(frame_dists) > 1 else 0.0

        return {
            "VCL":              round(vcl, 4),
            "VSL":              round(vsl, 4),
            "VAP":              round(vap, 4),
            "LIN":              round(lin, 4),
            "STR":              round(str_, 4),
            "WOB":              round(wob, 4),
            "ALH":              round(alh, 4),
            "total_distance":   round(total_distance, 4),
            "displacement":     round(displacement, 4),
        }

    # ----------------------------------------------------------

    def _classify_row(self, row: pd.Series) -> str:
        """
        Classify a track row into Progressive / Non-progressive / Immotile.

        Parameters
        ----------
        row : pd.Series

        Returns
        -------
        str
        """
        vcl = row["VCL"]
        lin = row["LIN"]

        if vcl < self.vcl_nonprog:
            return "Immotile"
        if vcl >= self.vcl_progressive and lin >= self.lin_progressive:
            return "Progressive"
        return "Non-progressive"

    # ----------------------------------------------------------

    def _build_summary(self, df: pd.DataFrame) -> Dict:
        """
        Build a summary dictionary from the per-track results.

        Returns
        -------
        dict
            Keys: progressive_pct, nonprogressive_pct, immotile_pct,
                  mean_VCL, mean_VSL, mean_VAP, total_tracks
        """
        n = len(df)
        counts = df["motility_class"].value_counts().to_dict()

        prog    = counts.get("Progressive",     0)
        nonprog = counts.get("Non-progressive", 0)
        immot   = counts.get("Immotile",        0)

        return {
            "total_tracks":       n,
            "progressive_count":  prog,
            "nonprogressive_count": nonprog,
            "immotile_count":     immot,
            "progressive_pct":    round(100 * prog    / n, 2) if n else 0.0,
            "nonprogressive_pct": round(100 * nonprog / n, 2) if n else 0.0,
            "immotile_pct":       round(100 * immot   / n, 2) if n else 0.0,
            "mean_VCL":           round(float(df["VCL"].mean()), 4),
            "mean_VSL":           round(float(df["VSL"].mean()), 4),
            "mean_VAP":           round(float(df["VAP"].mean()), 4),
        }

    # ----------------------------------------------------------

    def _plot_motility(self, df: pd.DataFrame) -> None:
        """
        Generate motility summary visualisations.

        1. Pie chart — Progressive / Non-progressive / Immotile
        2. Velocity distribution histograms (VCL, VSL, VAP)
        """
        fig, axes = plt.subplots(1, 3, figsize=(18, 5))
        fig.suptitle("Motility Analysis Results", fontsize=14, fontweight="bold")

        # ── Pie chart ──────────────────────────────────────────
        counts = df["motility_class"].value_counts()
        labels = counts.index.tolist()
        sizes  = counts.values.tolist()
        colors = {"Progressive": "#2ecc71", "Non-progressive": "#f39c12", "Immotile": "#e74c3c"}
        pie_colors = [colors.get(l, "#95a5a6") for l in labels]

        axes[0].pie(sizes, labels=labels, colors=pie_colors, autopct="%1.1f%%",
                    startangle=90, textprops={"fontsize": 11})
        axes[0].set_title("Motility Classification", fontweight="bold")

        # ── VCL distribution ───────────────────────────────────
        for cls, color in colors.items():
            subset = df[df["motility_class"] == cls]["VCL"]
            if not subset.empty:
                axes[1].hist(subset, bins=20, alpha=0.7, label=cls, color=color)
        axes[1].set_title("VCL Distribution (µm/s)")
        axes[1].set_xlabel("VCL (µm/s)")
        axes[1].set_ylabel("Frequency")
        axes[1].legend()
        axes[1].grid(True, alpha=0.3)

        # ── Velocity comparison bar ────────────────────────────
        means = [df["VCL"].mean(), df["VSL"].mean(), df["VAP"].mean()]
        stds  = [df["VCL"].std(),  df["VSL"].std(),  df["VAP"].std()]
        vnames = ["VCL", "VSL", "VAP"]
        bar_colors = ["#3498db", "#e74c3c", "#9b59b6"]

        bars = axes[2].bar(vnames, means, color=bar_colors, alpha=0.85, edgecolor="white")
        axes[2].errorbar(vnames, means, yerr=stds, fmt="none", color="black",
                         capsize=5, linewidth=2)
        axes[2].set_title("Mean Velocities ± SD (µm/s)")
        axes[2].set_ylabel("Velocity (µm/s)")
        axes[2].grid(True, alpha=0.3, axis="y")
        for bar, mean in zip(bars, means):
            axes[2].text(bar.get_x() + bar.get_width() / 2,
                         bar.get_height() + 0.5,
                         f"{mean:.1f}", ha="center", fontsize=10, fontweight="bold")

        plt.tight_layout()
        save_path = self.plot_dir / "motility_analysis.png"
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
        plt.close()
        logger.info("Motility plot saved → {}", save_path)


# ══════════════════════════════════════════════════════════════
# Demo / synthetic data generator (for testing without video)
# ══════════════════════════════════════════════════════════════

def generate_synthetic_tracks(n_tracks: int = 50,
                               n_frames: int = 100,
                               fps: float = 30.0) -> pd.DataFrame:
    """
    Generate synthetic track data for unit-testing the analyser.

    Parameters
    ----------
    n_tracks : int
    n_frames : int
    fps : float

    Returns
    -------
    pd.DataFrame
    """
    rows = []
    rng = np.random.default_rng(42)

    for tid in range(n_tracks):
        speed_px = rng.uniform(1, 30)    # pixels/frame
        angle = rng.uniform(0, 2 * np.pi)
        cx, cy = rng.uniform(50, 600), rng.uniform(50, 450)

        for fid in range(n_frames):
            # Add some random walk on top of directed motion
            cx += speed_px * np.cos(angle) + rng.normal(0, 1)
            cy += speed_px * np.sin(angle) + rng.normal(0, 1)
            rows.append({"frame_id": fid, "track_id": tid,
                         "cx": cx, "cy": cy,
                         "x1": cx - 10, "y1": cy - 10,
                         "x2": cx + 10, "y2": cy + 10,
                         "conf": rng.uniform(0.5, 0.99)})

    return pd.DataFrame(rows)


# ══════════════════════════════════════════════════════════════
# CLI entry point
# ══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CASA-inspired sperm motility analysis")
    parser.add_argument("--tracks", default=None,
                        help="Path to tracks.csv. If omitted, uses synthetic data.")
    args = parser.parse_args()

    cfg = load_config()
    analyser = MotilityAnalyser(cfg)

    if args.tracks:
        analyser.load_tracks(args.tracks)
    else:
        logger.info("No tracks file provided — using synthetic demo data")
        analyser._tracks_df = generate_synthetic_tracks()

    per_track_df, summary = analyser.analyse()
    print("\nMotility Summary:")
    for k, v in summary.items():
        print(f"  {k:25s}: {v}")